# Generated by Django 5.1 on 2025-05-19 18:10

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, upload_to=course.models.assignment_file_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='private_test_file',
            field=models.FileField(blank=True, upload_to=course.models.assignment_file_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='public_test_file',
            field=models.FileField(blank=True, upload_to=course.models.assignment_file_path),
        ),
    ]
