# Generated by Django 5.1 on 2025-05-20 17:57

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_assignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, upload_to=course.models.submission_file_path),
        ),
    ]
