# Generated by Django 5.1.1 on 2025-05-23 00:30

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_submission_submission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, max_length=255, upload_to=course.models.assignment_file_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='private_test_file',
            field=models.FileField(blank=True, max_length=255, upload_to=course.models.assignment_file_path),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='public_test_file',
            field=models.FileField(blank=True, max_length=255, upload_to=course.models.assignment_file_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, max_length=255, upload_to=course.models.submission_file_path),
        ),
    ]
