# Generated by Django 5.1.1 on 2025-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_assignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
