# Generated by Django 5.1.1 on 2025-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_submission_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.JSONField(default={}, max_length=1000),
            preserve_default=False,
        ),
    ]
