# Generated by Django 5.1.1 on 2025-06-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_assignment_rubric_alter_submission_splits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='reasoning',
        ),
    ]
