# Generated by Django 5.1.1 on 2025-06-12 17:24

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_submission_reasoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='solution_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=course.models.solution_file_path),
        ),
    ]
