export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as SignUp} from "./SignUp"
export {default as Dashboard} from "./Dashboard"
export {default as Courses} from "./Courses"
export {default as Assignments} from "./Assignments"
export {default as Marking} from "./Marking"
export {default as About} from "./About"